### ISSUE TITLE
Domein D

### ISSUE THREAD

**Issue by thehackerboi69github** [INFORMATICAFLIKKER/Domein-D#7]
# TODO

## Inleveropdrachten
- [x] Voeg voorbereiding opdracht toe
- [x] Voeg inleveropdracht D1 toe
- [x] Voeg inleveropdracht D2 toe
- [x] Voeg inleveropdracht D3 toe
- [ ] Voeg inleveropdracht D4 toe
- [ ] Voeg inleveropdracht D5 toe

## Fundament
- [x] Voeg 6 Python opdrachten toe
- [ ] Voeg alle Python opdrachten toe

## Sololearn
- [x] Voeg Python for Beginners projecten toe
